### ISSUE TITLE
报mysql的broken pipe错误

### ISSUE THREAD

**Issue by bjdudu** [btlike/storage#1]
2016/08/21 12:33:22 manager.go:62: xunlei未找到数量:810727,拒绝数量:182
2016/08/21 12:33:22 manager.go:64: 此次运行已存储数量: 70589
2016/08/21 12:34:22 manager.go:62: xunlei未找到数量:819678,拒绝数量:182
2016/08/21 12:34:22 manager.go:64: 此次运行已存储数量: 71227
2016/08/21 12:35:22 manager.go:62: xunlei未找到数量:829990,拒绝数量:182
2016/08/21 12:35:22 manager.go:64: 此次运行已存储数量: 71902
2016/08/21 12:36:22 manager.go:62: xunlei未找到数量:833060,拒绝数量:182
2016/08/21 12:36:22 manager.go:64: 此次运行已存储数量: 72097
[mysql] 2016/08/21 12:36:37 packets.go:33: unexpected EOF
[mysql] 2016/08/21 12:36:37 packets.go:124: write tcp 127.0.0.1:60661->127.0.0.1:3306: write: broken pipe
[mysql] 2016/08/21 12:36:37 packets.go:33: unexpected EOF
[mysql] 2016/08/21 12:36:37 packets.go:124: write tcp 127.0.0.1:60791->127.0.0.1:3306: write: broken pipe
[mysql] 2016/08/21 12:36:37 packets.go:33: unexpected EOF
[mysql] 2016/08/21 12:36:37 packets.go:124: write tcp 127.0.0.1:60789->127.0.0.1:3306: write: broken pipe
2016/08/21 12:37:22 manager.go:62: xunlei未找到数量:838398,拒绝数量:182
2016/08/21 12:37:22 manager.go:64: 此次运行已存储数量: 72536
2016/08/21 12:38:22 manager.go:62: xunlei未找到数量:846659,拒绝数量:183
2016/08/21 12:38:22 manager.go:64: 此次运行已存储数量: 73263
2016/08/21 12:39:22 manager.go:62: xunlei未找到数量:856818,拒绝数量:183
2016/08/21 12:39:22 manager.go:64: 此次运行已存储数量: 73910
2016/08/21 12:40:22 manager.go:62: xunlei未找到数量:865123,拒绝数量:186
2016/08/21 12:40:22 manager.go:64: 此次运行已存储数量: 74284

**Comment by btfak** [comment]
正常情况，只是一个警告
